### ISSUE TITLE
When S is large the codes does not run

### ISSUE THREAD

**Issue by NedaJalali-codes** [tjmckinley/SimBIID#9] opened 2020-04-16 21:24 UTC
Hey,
I am trying to run a SIR model with initialzing values at
iniStates <- c(S = 1000000, I = 1, R = 0). 
But the codes do can not give the results and the process gets stuck after the following lines:
Initial states:
state[0] = 1000000
state[1] = 1
state[2] = 0

Initialising system...
Initialisation complete!

Initial parameter values:

beta = 3.54364
gamma = 2.1883

Starting runs...

Any idea why it happens?

Best,
Neda

**Comment by NedaJalali-codes** [comment] 2020-04-16 21:28
Sorry, S is equal to 10,000,000

**Comment by tjmckinley** [comment] 2020-04-17 08:55
Hi Neda, 

Can you clarify what you are running please? It looks like you're running PMCMC. Is this correct? If so, then with a population size of 10,000,000 the Gillespie simulation algorithm can be very slow. One thing you could do is to change the argument `nprintsum` in the `PMCMC()` function so that it prints to the screen more often (try `nprintsum = 10` or something to test this out).

If this is too slow, then a package like `pomp` has a much faster simulation algorithm and will also implement PMCMC.

Many thanks,

TJ

**Comment by NedaJalali-codes** [comment] 2020-04-17 12:19
Hi TJ,
That is right. I am running PMCMC. 
Thank you so much for your help.

Best,
Neda

**Comment by tjmckinley** [comment] 2020-04-17 12:22
Hi Neda,

OK, let me know how it goes with the suggestions above.

Many thanks,

TJ

**Comment by NedaJalali-codes** [comment] 2020-04-17 14:35
TJ, 
I tried "nprintsum = 1" to see how long each iteration takes. It was pretty fast until i = 252 and then after that, running each iteration was slow and it got stuck by i = 380.

Best, 
Neda

**Comment by tjmckinley** [comment] 2020-04-17 15:07
Hi Neda,

I suspect this is caused by the PMCMC getting into a part of the parameter space which results in large numbers of infections. With the Gillespie simulation algorithm this can be very slow. It's not throwing an obvious error.

Do you have a minimal reproducible example to hand?

Many thanks,

TJ

**Comment by NedaJalali-codes** [comment] 2020-04-17 15:48
You are right, TJ. 
It can not handle large number of infections. I tried 10 times with a large number of infections at each time and it was slow. 

Thank you for your help. 
Neda

**Comment by tjmckinley** [comment] 2020-04-17 16:00
Hi Neda,

I think it can handle it (i.e. there's no error), it's just rather slow because of the large number of infections in a large background population. You could look at `pomp` as an alternative, although PMCMC is likely to be slow in any population of that size unless you are restricted to areas of the parameter space that only induce low numbers of infections.

If there's no error, then I'll close the issue.

Good luck.

TJ

**Closed as completed by tjmckinley** 2020-04-17 16:00 UTC
